version: '3'
services:
  web:
    build:
      context: ../../todo-api
      dockerfile: ../docker/development/Dockerfile
    volumes:
      - web-data:/app
    ports:
      - "3000:3000"
volumes:
  web-data:
    driver: local